/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 *
 * VSched is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *      http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef VIRTAWARESCHED_TEST_LOGGER_H
#define VIRTAWARESCHED_TEST_LOGGER_H

#include "gtest/gtest.h"

#include "logger.h"

namespace vas::ut::logger {
    class TestLogger : public testing::Test {
    protected:
        TestLogger() = default;

        void SetUp() override
        {
            // Initializing the Test Environment
            testing::Test::SetUp();
            // Set log path and file
            logPath_ = "/tmp/test_logs";
            logFile_ = "test.log";
            // Deleting Old Log Files
            if (std::filesystem::exists(logPath_)) {
                std::filesystem::remove_all(logPath_);
            }
            std::filesystem::create_directories(logPath_);
        }

        void TearDown() override
        {
            // Clean up test environment
            testing::Test::TearDown();
            // Delete log files generated by testing
            if (std::filesystem::exists(logPath_)) {
                std::filesystem::remove_all(logPath_);
            }
        }

    private:
        std::string logPath_;
        std::string logFile_;
    };

} // namespace vas::ut::logger
#endif // VIRTAWARESCHED_TEST_LOGGER_H
